# For testing out my actions
name: Test Actions
on: 
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup
      - run: echo "success!!"
