# For testing out my actions
name: Test Actions
on: 
  workflow_dispatch:
    branches: '*'

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup
      - run: echo "success!!"
